### ISSUE TITLE
Backend using firebase

### ISSUE THREAD

**Issue by lamquangphuc** [jvitor83/angular-pwa-seed#12]
Can you change backend database to firebase?

**Comment by jvitor83** [comment]
Actually i don't have any "backend database" configured!
I think you are asking about "Authentication using Firebase" right?
If it is, i am planning to change the https://github.com/jvitor83/angular-pwa-seed/blob/master/src/app/shared/services/auth.service.ts to a strategy of creating an Abstract Class or Interface like a BaseAuthService where you can then choose between an AuthService implementation using "Firebase Authentication", "OIDC Client" or even create a custom one.

I don't have yet a date release to this, but i think will not take much longer.
