### ISSUE TITLE
NPM Error in starting the project

### ISSUE THREAD

**Issue by smarzougui** [jvitor83/angular-pwa-seed#20]
Hello all,

The project cloned
npm runned successfully.

And this is what I get trying to run it:

─smarzougui@smarzougui-VirtualBox /var/www/private-projects/angular-pwa-seed  ‹master› 
╰─$ sudo npm run start             

> angular-pwa-seed@0.1.0 start /var/www/private-projects/angular-pwa-seed
> npm run ng -- serve --port 5555

> angular-pwa-seed@0.1.0 ng /var/www/private-projects/angular-pwa-seed
> ng "serve" "--port" "5555"

/var/www/private-projects/angular-pwa-seed/node_modules/@angular/cli/models/config/config.js:17
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/private-projects/angular-pwa-seed/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/var/www/private-projects/angular-pwa-seed/node_modules/.bin/npm" "run" "ng" "--" "serve" "--port" "5555"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE
npm ERR! angular-pwa-seed@0.1.0 ng: `ng "serve" "--port" "5555"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-pwa-seed@0.1.0 ng script 'ng "serve" "--port" "5555"'.
npm ERR! This is most likely a problem with the angular-pwa-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng "serve" "--port" "5555"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-pwa-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls angular-pwa-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/private-projects/angular-pwa-seed/npm-debug.log

npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! angular-pwa-seed@0.1.0 start: `npm run ng -- serve --port 5555`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-pwa-seed@0.1.0 start script 'npm run ng -- serve --port 5555'.
npm ERR! This is most likely a problem with the angular-pwa-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run ng -- serve --port 5555
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-pwa-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls angular-pwa-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/private-projects/angular-pwa-seed/npm-debug.log

**Comment by jvitor83** [comment]
I can't say if this problem has something to do with your node version, but can you try to update your nodejs version to at least 6?
Report back if solved or it persist!

**Comment by jvitor83** [comment]
Closed due to non response.
