### ISSUE TITLE
Components location

### ISSUE THREAD

**Issue by markzolotoy** [jvitor83/angular-pwa-seed#29]
You are providing a location for Angular components as a single file. But my understanding it's supposed to be a folder named Components where all Angular components are going to be. Can  you please clarify?

Thanks

**Comment by jvitor83** [comment]
I am not providing a location as a single file.
Your components should be at `src\app`, as specified in readme.

**Comment by markzolotoy** [comment]
Ah, I see what you are saying. So, I have to add some additional Angular attributes to the project you are providing? I am new to Ionic/Angular development and trying to find a project structure that I dont need to change but can start developing my application with it.

**Comment by jvitor83** [comment]
I don't understand what you mean by "add some additional Angular attributes to the project", but it's just like any other angular app.
