### ISSUE TITLE
Error cloning the project

### ISSUE THREAD

**Issue by markzolotoy** [jvitor83/angular-pwa-seed#30]
I am trying cloning the project by running the following:
**PS D:\angular-pwa-seed> git clone https://github.com/jvitor83/angular-pwa-seed.git AngIonic1
Cloning into 'AngIonic1'.**..
fatal: unable to access 'https://github.com/jvitor83/angular-pwa-seed.git/': error setting certificate verify locations:
  CAfile: C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt

**Comment by jvitor83** [comment]
I have no idea why this are happening with you.
But check if NPM and GIT versions installed are compatible with the requirements at README.
My guess is that is something related to your environment and nothing to do with my specific repository (or seed).

**Comment by markzolotoy** [comment]
When you say check readme am I looking at @angular/cli@1.7.1 cordova@6.5.0
ionic@2.2.3?
Are these the versions I must use?

**Comment by jvitor83** [comment]
Yes.
But as i said, my guess is that it is something related to your environment.
Check [this issue](https://stackoverflow.com/questions/3778042/github-error-cloning-my-private-repository) and look if it solves your problem

`git config --global http.sslverify "false"`

**Comment by markzolotoy** [comment]
Actually, I was able to clone the project. Thanks for your help.
