### ISSUE TITLE
Executing npm install never finishes

### ISSUE THREAD

**Issue by markzolotoy** [jvitor83/angular-pwa-seed#31]
After cloning the project I am running npm install. Here is what I get
PS K:\Project1> npm install
npm WARN tar ENOENT: no such file or directory, open 'K:\Project1\node_modules\.staging\nan-1c7803b7\doc\new.md'
npm WARN tar ENOENT: no such file or directory, open 'K:\Project1\node_modules\.staging\nan-1c7803b7\doc\asyncworker.md'
npm WARN tar ENOENT: no such file or directory, open 'K:\Project1\node_modules\.staging\nan-1c7803b7\doc\callback.md'
npm WARN tar ENOENT: no such file or directory, open 'K:\Project1\node_modules\.staging\nan-1c7803b7\doc\converters.md'
npm WARN tar ENOENT: no such file or directory, open 'K:\Project1\node_modules\.staging\nan-1c7803b7\doc\errors.md'
npm WARN tar ENOENT: no such file or directory, open 'K:\Project1\node_modules\.staging\nan-1c7803b7\doc\json.md'
npm WARN tar ENOENT: no such file or directory, open 'K:\Project1\node_modules\.staging\nan-1c7803b7\doc\maybe_types.md'
npm WARN angular-pwa-seed@0.1.0 No repository field.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for asn1.js@4.10.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'angular-pwa-seed'
npm ERR! notarget

And the command is not finishing.

Actually it did finish. Should I be concerned with errors?

I guess, I should be because next command did not work at all:

PS K:\Project1> npm run start

> angular-pwa-seed@0.1.0 start K:\Project1
> npm run ng -- serve --port 5555 --aot

> angular-pwa-seed@0.1.0 ng K:\Project1
> ng "serve" "--port" "5555" "--aot"

'ng' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-pwa-seed@0.1.0 ng: `ng "serve" "--port" "5555" "--aot"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-pwa-seed@0.1.0 ng script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mark\AppData\Roaming\npm-cache\_logs\2018-03-22T09_10_42_892Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-pwa-seed@0.1.0 start: `npm run ng -- serve --port 5555 --aot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-pwa-seed@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mark\AppData\Roaming\npm-cache\_logs\2018-03-22T09_10_42_923Z-debug.log

Can you please help?

Thanks

**Comment by thomascayne** [comment]
I had the same experience yesterday. Didn't finish. Aborted. Retry didn't work. Aborted.

**Comment by jvitor83** [comment]
What are your node and npm versions?

**Comment by markzolotoy** [comment]
Node - v 8.9.4
npm- 5.6.0

**Comment by jvitor83** [comment]
Guys, i am really sorry, but i wan't able to reproduce your problem.
I even reinstall node and do a git clone, but it worked just fine.

Can you please try to clear the cache, or even reinstall node and try again?

**Comment by markzolotoy** [comment]
Which cache to clear?

**Comment by jvitor83** [comment]
`npm cache clean`

https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache

**Comment by markzolotoy** [comment]
Did not help.

**Comment by rodolfocop** [comment]
Hi, try this please.

```
rm -rf package-lock.json 
rm -rf node_modules
npm cache clean --force
npm install
```

**Comment by markzolotoy** [comment]
PS K:\Project1> rm -rf package-lock.json
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:4
+ rm -rf package-lock.json
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by jvitor83** [comment]
1 - DELETE the file `package-lock.json`
2 - DELETE the directory `node_modules`
3 - RUN `npm cache clean --force`
4 - RUN `npm install`

**Comment by thomascayne** [comment]
I'm marking this as resolved (on my part). @markzolotoy , maybe you can try this: I deleted my _node_modules_ folder; followed [the installation steps](https://github.com/jvitor83/angular-pwa-seed#starting) using `npm` and it still hangs, again.

After it failed, this time I ran `yarn` [install]. Other than warnings for peer dependencies all packages were installed. 

`npm run start` and `ng serve` now works.

@jvitor83 great job on this project. Beautifully done. Thank you!

**Comment by jvitor83** [comment]
My guess is that the `package-lock.json` is causing the trouble.
I think the 4 steps i put solve the problem.
@markzolotoy, open it again if not works for you.

**Comment by markzolotoy** [comment]
Yes, these four steps helped. Thank you! For the future reference what exactly it was? I do get a few warnings:
WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js
27:11-36 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js
37:11-36 Critical dependency: the request of a dependency is an expression

Is it critical?

**Comment by rodolfocop** [comment]
@markzolotoy this not problem, you can see [here](https://github.com/ionic-team/ionic/issues/11072) explanation.
