### ISSUE TITLE
Server side technologies

### ISSUE THREAD

**Issue by markzolotoy** [jvitor83/angular-pwa-seed#32]
Are you using MEAN stack for the server side? If not, what do I need to get familiar with to code the backend that you are using in your seed project?

Thanks

**Comment by jvitor83** [comment]
I have no intention to define or induce any server side technologie.
The only factor i set was the OAuth authentication. But any server-side can be used.
I put a `web.config` file to ease the publish (to allow .json files as response) to a IIS web server (commonly used in a .NET environment), but can be published in any web server as well (ie: my dockerfile use nginx).

As said, you can choose any backend tech you want.
