### ISSUE TITLE
Ng2 Translate integration

### ISSUE THREAD

**Issue by setbusiness** [jvitor83/angular-pwa-seed#8]
Hi,

i try to integrate ng2-translate but i have a bug because the translation update only the current page(not over layout). Example: i'm on Dashboard, i insert ng2 translate, only this component work.

**On my app.component:**
`import { Component, ViewEncapsulation, ViewChild, ElementRef, OnInit, AfterContentInit, ApplicationRef } from '@angular/core';
import { TranslateService } from 'ng2-translate';
import { Platform, MenuController } from 'ionic-angular';
import { StatusBar, Splashscreen } from 'ionic-native';
import { Storage } from '@ionic/storage';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {

  constructor(
    public platform: Platform,
    public translate: TranslateService,
    public menu: MenuController,
    public application: ApplicationRef,
    private storage: Storage,
  ) {
    this.initializeApp();

    this.translate.setDefaultLang('fr');
		storage.get('language').then((value) => {
			if (value) {
				this.translate.use(value);
			} else {
				this.translate.use('fr');
				this.storage.set('language', 'fr');
			}
		});
  }`

**My shared.module**
`import { NgModule } from '@angular/core';
import { IonicModule } from 'ionic-angular';
import { Storage } from '@ionic/storage';
//import { CommonModule } from '@angular/common';
import { HttpModule, Http } from '@angular/http';
import { TranslateModule, TranslateLoader, TranslateStaticLoader } from 'ng2-translate';

import { TruncatePipe } from './pipes/truncate.pipe';
import { TrimHtmlPipe } from './pipes/trim-html.pipe';

import { Config } from '../app.config';

//import { MyApp } from '../app.component';

export function createTranslateLoader(http: Http) {
    return new TranslateStaticLoader(http, './assets/translations', '.json');
}

@NgModule({
  declarations: [
    TruncatePipe,
    TrimHtmlPipe
  ],
  imports: [
    HttpModule,
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [Http]
    })
  ],
  exports: [
    IonicModule,
    TranslateModule,
    TruncatePipe,
    TrimHtmlPipe
  ],
  providers: [
    Config,
    Storage
  ]
})
export class SharedModule {
  constructor(private translate: TranslateService, private storage: Storage) {
        this.translate.setDefaultLang('fr');
        storage.get('language').then((value) => {
          if (value) {
            this.translate.use(value);
          } else {
            this.translate.use('fr');
            this.storage.set('language', 'fr');
          }
        });
     }
}
`

**Comment by jvitor83** [comment]
Sorry, i don't have much knowledge about ng2-translate. 
But maybe has something to do with Lazy Loading Modules.
Anyway, you should be updating your seed to use this latest version and look again if the problem persist.
I you continue to get this problem, feel free to reopen this issue.
